name: medscore
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - backoff
      - faiss-cpu==1.9.0
      - huggingface-hub==0.34.3
      - jsonlines==4.0.0
      - numpy==2.2.4
      - openai==1.93.0
      - overrides
      - pandas
      - pydantic==2.10.6
      - pyyaml
      - registrable==0.0.4
      - regex
      - requests
      - tqdm
      - spacy==3.7.4  # Consistency with original paper
      - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
      - nest_asyncio
      - sentence-transformers
      - python-dotenv
