name: medscore
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - backoff
      - faiss-cpu==1.9.0
      - huggingface-hub==0.34.3
      - jsonlines==4.0.0
      - numpy==2.2.4
      - openai==1.93.0
      - overrides
      - pandas
      - pydantic==2.10.6
      - pyyaml
      - registrable==0.0.4
      - regex
      - requests
      - tqdm
      - spacy==3.8.4  # original paper uses 3.7.4
      - nest_asyncio
      - sentence_transformers
      - python-dotenv
